//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCTP_GA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string ClassId { get; set; }
        public string CourseId { get; set; }
        public string SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> NumberOfStudents { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> SKS { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
