//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCTP_GA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Populations = new HashSet<Population>();
        }
    
        public string ScheduleId { get; set; }
        public string ClassId { get; set; }
        public string TimeId { get; set; }
        public string RoomId { get; set; }
        public string LecturerId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Population> Populations { get; set; }
        public virtual Room Room { get; set; }
        public virtual Time Time { get; set; }
    }
}
